#! /bin/bash
clear
function Menu(){
 echo -e "1. Create user\n2. Delete user\n3. Create group\n4. Delete group\n5. Edit user\n6. Show info\n0. Exit"
 read choice
}

function CreateUser (){
 clear
 echo -e "1) Name\n2) Name + UID + GID"
 read userChoice

 if (( $userChoice == 1 ))
 then
   echo "Enter username: "
   read newUserName
   cat /etc/passwd | grep $newUserName
   if (( $? == 0 ))
   then
     echo "User exist!"
   else
     useradd $newUserName
     passwd $newUserName
  fi
 elif (( $userChoice == 2 ))
 then
    echo "User choice 2"
 else
   echo "Wrong choice"
 fi

}



exit=true

while [ $exit == true ]
do
 Menu;
 case $choice in
   1) CreateUser; ;;
   0) echo "Bye!"; let exit=false ;;
   *) echo "R.T.F.M."; ;;
 esac
done



function Sum (){
 local PARAM_1="$1";
 local PARAM_2="$2";

 echo -e "PRAM_1 = ${PARAM_1}\nPARAM_2 = ${PARAM_2}";
}

Sum "5" "10"
